title: 0xarch 的博客
additional_title: 0xarch's Blog!
description: |-
  This is the blog website of 0xarch from GitHub, see https://github.com/0xarch/0xarch.github.io for the source code.
note: |-
  I could be myself out there. Bullying, reckless, totally selfish. Doing the things that makes me me.
  If you ain't who you are, then who the fuck are you?
author: 0xarch
language: zh-CN
timezone: Asia/Shanghai
url: https://0xarch.github.io
root: /
source_dir: source
public_dir: public
theme: "fewu-theme-next"
theme_next:
  accent_color: 295
  additional_navs:
    About: /article/FZNPAGaQQ0UXmZdz/
    GitHub:
      isExternal: true
      url: https://github.com/0xarch/
      title: GitHub
  banner:
    url: https://webstatic.mihoyo.com/upload/op-public/2022/04/27/f735b165fde7065224db246e817baf5e_7146177856182195094.png
    credit: MiHoYo
    credit_url: https://sr.mihoyo.com/
excluded_files: 
  - posts\template.md
  - posts\guide\guide.zh-CN.md
  - posts\guide\guide.en-US.md
footer_content: |
  © 2019-2025 0xarch & Soloev. All Rights Reserved. / <a href="/feed.xml">RSS</a> / <a href="/sitemap.xml">Sitemap</a>
social_links:
  GitHub:
    url: https://github.com/0xarch
    icon: fa-github
  Bilibili:
    url: https://space.bilibili.com/582594431
    icon: fa-bilibili
plugin_configs:
  fewu-plugin-basic-improvement:
    rss:
      enabled: true
    sitemap:
      enabled: true
      type: xml
    extra-files:
      enabled: true
      from: ./extra
      files:
        - smq.html
        - robots.txt
_custom_giscus: |
  <script src="https://giscus.app/client.js"
          data-repo="0xarch/0xarch.github.io"
          data-repo-id="R_kgDOJlXk8A"
          data-category="Announcements"
          data-category-id="DIC_kwDOJlXk8M4Cl1VA"
          data-mapping="pathname"
          data-strict="1"
          data-reactions-enabled="1"
          data-emit-metadata="0"
          data-input-position="top"
          data-theme="preferred_color_scheme"
          data-lang="zh-CN"
          data-loading="lazy"
          crossorigin="anonymous"
          async>
  </script>